#	Makefile generated by imake - do not edit!
#	$XConsortium: imake.c,v 1.51 89/12/12 12:37:30 jim Exp $
#
#	The cpp used on this machine replaces all newlines and multiple tabs and
#	spaces in a macro expansion with a single space. Imake tries to compensate
#	for this, but is not always successful.
#

#
#	This template is not automatically generated by imake, and can
#	be found in PLS UNXDEV as IMKDATAS. This file was generated from
#	the UAE IMKOPC template produced by 7B21.
#

		DEPEND		= makedepend
		IMAKE		= imake

# 34

# 41

# 48

# 62

# 67

		SHELL		= /bin/ksh
		TOP			= $(TOPDIR)
		AS			= as
		CC			= cc
		CPP			= /lib/cpp
		CP			= cp -f
		LD			= ld
		LINT		= lint
		INSTALL		= /lbtools/bin/bsdinstall
		TAGS		= ctags
		RM			= rm -f
		MV			= mv
		LN			= ln -s
		AR			= ar rcul
		RANLIB		= ranlib
		LS			= ls
		LINTOPTS	= -ax
		LINTLIBFLAG	= -o
		MAKE		= make
		STD_DEFINES	= -DSYSV
		CDEBUGFLAGS	= -O

#	78

		DEFINES		= -DDEBUG

#	84

		PATHSEP		= /
		CFLAGS		= $(CDEBUGFLAGS) $(INCLUDES) $(STD_DEFINES) $(DEFINES)
		LINTFLAGS	= $(LINTOPTS) $(INCLUDES) $(STD_DEFINES) $(DEFINES) -DLINT

		LDFLAGS		= $(CDEBUGFLAGS) $(LIBSEARCHDIRS)

#	94

		INSTUIDFLAGS = -m 4755
		INSTLIBFLAGS = -m 0664
		INSTINCFLAGS = -m 0444
		INSTMANFLAGS = -m 0444
		INSTAPPFLAGS = -m 0444
		INSTALLFLAGS = -m 0775

		INSTALL = /itdserv/bin/bsdinstall

		INCLUDES	= $(IPATH)
		MACROFILE	= imkhpux.macros
		IMAKE_CMD	= $(IMAKE) -s Makefile
		RM_CMD		= if [ -d ptrepository ]; then rm -r ptrepository; fi; \
					  $(RM) *.CKP *.In *.BAK *.bak *.o core errs ,* *" *.a \
					  tags TAGS tnake.log *.uidt *.uili
		UIDT		= uidt
		UIDLFLAGS	=

.uidl.uidt:
		$(UIDT) $(UIDLFLAGS) -o $*.uidt $<

.uidl.uili:
		$(UIDT) $(UIDLFLAGS) -C $<

.SUFFIXES: .uidl .uidt .uili

# 132

# 144

# 105

# 146

# 284

# 296

		RELEASE		= "2.11"
		VERSION		= "ATP.AC12"
		OPSYS		= 'uname -srvm'

		SRC_DIR		= .

		CC			= cc
		CC			= CC -w
		CC			= cc -Aa -D_HPUX_SOURCE

		CDEBUGFLAGS	= -g -DDEBUG

# 49

LIBSRCS =	atp2tcl.c atpalloc.c atpbcdpm.c atpbool.c atpcase.c \
			atpcheck.c atpchois.c atpcmd.c atpcmplx.c atpdebug.c \
			atpdynam.c atperror.c atpfindp.c atpfrarae.c atphelp.c \
			atphelpc.c atphexpm.c atpinit.c atpkeywd.c atplist.c \
			atpmanpg.c atpmem.c atpnullp.c atpnum.c atppage.c \
			atpparse.c	atppmchk.c	atppmdef.c	atppmptr.c \
			atprpblk.e atpstcmp.c atpstr.c atptoken.c atpusrio.c

LIBOBJS =	atp2tcl.o atpalloc.o atpbcdpm.o atpbool.o atpcase.o \
			atpcheck.o atpchois.o atpcmd.o atpcmplx.o atpdebug.o \
			atpdynam.o atperror.o atpfindp.o atpframe.o atphelp.o \
			atphelpc.o atphexpm.o atpinit.o atpkeywd.o atplist.o \
			atpmanpg.o atpmem.o atpnullp.o atpnum.o atppage.o \
			atpparse.o	atppmchk.o	atppmdef.o	atppmptr.o \
			atprpblk.o atpstcmp.o atpstr.o atptoken.o atpusrio.o

	OBJS	= $(LIBOBJS) atpexmp.o

	SRCS	= $(LIBSRCS) atpexmp.c

	SYS_LIBRARIES	= -lm -lmalloc
	BASE_LIBRARIES	= -lslp -ltd -latp
	APPL_LIBRARIES	= 

all:: libatp.a atpexmp

.c.o:
		$(RM) $@
		$(CC) -c $(CFLAGS) $* . c

all:: libatp.a

libatp.a: $(LIBOBJS)
		  $(RM) $@
		  $(AR) $@ $(LIBOBJS)
		  $(RANLIB) $@

atpexmp: libatp.a atpexmp.o

atpexmp: atpexmp.o	\
		 $(APPL_LIBRARIES)
		 $(RM) $@
		 $(CC) -o $@ atpexmp.o	\
					 $(APPL_LIBRARIES) $(LDFLAGS)		\
					 $(BASE_LIBRARIES) $(SYS_LIBRARIES)
relink::
		 $(RM) atpexmp
		 $(MAKE) $(MFLAGS) atpexmp

clean::
		 $(RM) atpexmp

# 102

EXTRACT_TESTS="\nExtracting ATP test suites...\n"
TESTDIR_CREATED="\nATP test suites directory \"atptests\" created.\n”
UNCOMPRESS_TARZ="\nUncompress atptests.tar.Z...\n"

test: libatp.a atpexmp

		@if [ -d atptests ] ; \
		then \
: # Do nothing \
		elif [ -f atptests.tar ] ; \
	then \
	echo $(EXTRACT_TESTS); \
	tar -xvf atptests.tar; \
	rm atptests.tar; \
	echo ${TESTDIR_CREATED); \
	elif [ -f atptests.tar.Z ] ; \
	then \
	echo $(UNCOMPRESS_TARZ); \
	uncompress atptests.tar.Z; \
	echo $(EXTRACT_TESTS); \
	tar -xvf atptests.tar; \
	rm atptests.tar; \
	echo $(TESTDIR_CREATED); \
	elif [ -f atptests.tarz ] ; \
	then \
	ln -s atptests.tarz atptests.tar.Z ; \
	echo $(UNCOMPRESSJTARZ); \
	uncompress atptests.tar.Z; \
	if [ ! -f atptests.tar ] ; \
	then \
	echo "\007\007\007\007\007\007n;\
	echo "Don't worry. I'll fix it.";\
	rm atptests.tar.Z ; \
	mv atptests.tarz atptests.tar ; \
	cp atptests.tar atptests.tmp ; \
	compress atptests.tmp ; \
	mv atptests.tmp.Z atptests.tarz ; \
	echo "\007\007\007\007\007\007";\
	echo "DONE - Fixed atptests.tarz";\
	echo "\007\007\007\007\007\007";\
	fi ; \
	echo $(EXTRACT_TESTS); \
	tar -xvf atptests.tar; \
	rm atptests.tar; \
	echo $(TESTDIR_CREATED); \
	else \
	echo "\nTest suites directory \"atptests\" missing.";\
	echo "Original TARZ file \"atptests.tarz\" missing.";\
	echo "Compressed tar file \"atptests.tar.Z\" not found.";\
	echo "Uncompressed tar file \"atptests.tar\" not found.";\
	exit 1; \
	fi ; \
	cwd=`pwd`; \
	cd $$cwd; ( echo ed $(SRC_DIR)/atptests ; echo source defs ; echo source all ) | ./atpexmp -oAutoTest

all:: stampload

stampload:
		@set +e +x ; \
		for i in libatp.a atpexmp,- do \
		what $$i | grep "ITD LOADBUILD DETAILS" >/dev/null ; \
		case $$? in 1) \
		echo "lm>»»> Stamping loadbuild details to $$i...m";\
		echo "\
char _Loadbuild_Details_`date +%y%m%d_%H%M%S`[] = \"\\
@(#)ITD LOADBUILD DETAILS\\\n\\
@(#)---------------------\\\n\\
@(#)Build date: `date '+%d/%m/%y %X'`\\\n\\
@(#)Built by:	`logname`\\\n\\
@(#)Built on:	`hostname`\\\n\\
@(#)Release:	${RELEASE}\\\n\\
@(#)Version:	${VERSION}\\\n\\
@(#)Compile:	${CC} ${CDEBUGFLAGS} ${DEFINES} ${CCFLAGS}\\\n\\
@(#)Context:\\\n\\
				`ls -l /itdserv/Contexts/${CNTX}/* | \
				awk '{printf(\"@(#) %s {%s)\\\\\\\\n\\\\\\n\"),$$9,$$ll}'`\\
@(#)Operating system: ${OPSYS}\"; " > _lbld_details_$$$$.c \
		cc -c __lbld_details_$$S$.c ; \
		ar t $$i 2>/dev/null l>/dev/null; \
		if [ $$? = 0 ] ; \
		then \
		ar q $$i __lbld_details_$$$$.o ; \
		else \
		cat ___lbld_details_$$$$.o >> $$i ; \
		fi ; \
		rm -f __lbld_details_$$$$.[co] ;; \
		*) fi \
		esac ; \
		done

all::	PurifySuppressions

PurifySuppressions:
		@if [ -f atpimake.imk ] ; \
\
		then \
\
		grep ^suppress atpimake.imk > .purify ;\
\
		fi

all:: MakeTestAndlnstalllnstructions

MakeTestAndlnstalllnstructions::
		@echo "\nlibatp.a and atpexmp OK."; \
		echo "Type \"lmmake testm\" to test ATP."; \
		echo "Type \"make install\" to install ATP system.\n”

install:: atph.h
		$(INSTALL) -c $(INSTINCFLAGS) atph.h $(INCDIR)

install:: atp2tclh.h
		$(INSTALL) -c $(INSTINCFLAGS) atp2tclh.h	$(INCDIR)

install:: libatp.a
		$(INSTALL) -c $(INSTLIBFLAGS) libatp.a $(LIBDIR)
		$(RANLIB)	$(LIBDIR)/libatp.a

install:: atpexmp
		$(INSTALL) -c $(INSTALLFLAGS) atpexmp $(BINDIR)

depend::
		$(DEPEND) -S "# DO NOT DELETE" $(CFLAGS) $(SRCS)

atpexmp.cents:
		#load $(IPATH)			\
						atpexmp.o
		#load -L. -L$(L) -L/ae/$(UAEVER)/uae/lib			\
						$(BASE_LIBRARIES) $(SYS_LIBRARIES)

atpexmp.cento:
		#load $(IPATH) atpexmp.c
		#load -L. -L$(L) -L/ae/$(UAEVER)/uae/lib			\
						 $(BASE_LIBRARIES) $(SYS_LIBRARIES)
# 293

clean::
		$(RM_CMD) \#*

Makefile::	Imakefile \
			$(IRULESRC)/Imake.rules \
			$(IRULESRC)/$(MACROFILE)
			-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
			$(IMAKE_CMD) -DTOPDIR=$(TOP)

tags::
			$(TAGS) -tw *.[ch]

.c.o:
			$(RM) $@
			@set -e ;	\
			echo "»»» Adding pis id to $<" ;	\
			fname=` echo $< | sed -e 's/\..$$//' `; \
			vers=`head -1 $<|awk ' $$2=="EDITION" {printf "%s %s %s %s\t%s %s %s", $$3, $$4, $$5, $$6, $$7, $$8, $$10}' | \
					tr '[A-Z]' '[a-z]'`; \
			issue=`echo $$vers | cut -d\	-f1`; \
			id=$${vers:='**** (******), *** ***.***\t('`date "+%y/%m/%d %T"`') *****'};	\
			echo "#ifndef PLSID_DEFINED" > $<.id ; \
			echo "#define PLSID_DEFINED" >> $<.id ; \
			echo "static char *whatid = \"@(#) $$fname. $$id\"; " >> $<.id ;	\
			echo "static char *plsid = \"$$issue\";" >> $<.id ;	\	,
			echo "#endif" >> $<.id ; \
			echo "#line 1" >> $<.id ; \
			mv $< $<.C; cat $<.id $<.C > $<; chmod +w $<;	\
			trap '' 2 3 15;	\
			trap 'mv $<.C $<; rm -f $<.id $(<:.c=.o)' ERR; \
			echo $(CC) $(CFLAGS) -c $<;	\
			$(CC) $(CFLAGS) -c $<; mv $<.C $< ; rm -f $<.id

.cxx.o:
			$(RM) $@
					@echo ">>>>>> Adding pis id to $<" ;	\
					fname=` echo $< | sed -e ’s/\..$$//’ `;	\
					vers=`head -1 $<|awk '$$2=="EDITION"{printf "%s %s %s %s\t%s %s %s",$$3,$$4,$$5,$$6,$$7,$$8,$$10}'| tr '[A-Z]' '[a-z]'`
					issue=`echo $$vers | cut -d\ -f1`; \
					id=$${vers : =' **** (******), *** *** . ***\t ('`date "+%y/%m/%d %T"`') ******'}; \
					echo "static char *whatid = \"@(#)$$fname.$$id\";" > $*.what_id.c; \
					echo "static char *plsid = \"$$issue\";" >> $*.what_id.c ;	\
			$(CC) $(CFLAGS) -Aa -w -c $*.what_id.c
			$(CC) $(CFLAGS) -c $*.cxx -o $@
			@cat $*.what_id.o >>$@
			@$(RM) $*.what_id.*

# 248

install::
			@echo "install done"

Makefiles::

# DO NOT DELETE

atp2tcl.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h
atp2tcl.o: /usr/include/stdlib.h /usr/include/malloc.h
atp2tcl.o: /usr/include/sys/types.h /usr/include/string.h
atp2tcl.o: /usr/include/unistd.h /usr/include/sys/unistd.h
atp2tcl.o: /usr/include/ctype.h /itdserv/Contexts/g2config.aa07/tcl/inc/tcl.h
atp2tcl.o: /usr/include/varargs.h atp2tclh.h atph.h
atpalloc.o: /usr/include/unistd.h /usr/include/sys/unistd.h
atpalloc.o: /usr/include/stddef.h /usr/include/sys/stdsyms.h
atpalloc.o: /usr/include/malloc.h /usr/include/sys/types.h atph.h
atpalloc.o: /usr/include/varargs.h atpsysex.h /usr/include/sys/stat.h
atpalloc.o: /usr/include/string.h /usr/include/signal.h
atpalloc.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpalloc.o: /usr/include/ctype.h /usr/include/setjmp.h /usr/include/assert.h
atpalloc.o: /usr/include/memory.h /usr/include/stdio.h
atpbcdpm.o: /usr/include/ctype.h /usr/include/string.h /usr/include/stdlib.h
atpbcdpm.o: at.ph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpbcdpm.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpbcdpm.o: /usr/include/sys/stat.h /usr/include/signal.h
atpbcdpm.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpbcdpm.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpbcdpm.o: /usr/include/memory.h /usr/include/stdio.h
atpbool.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpbool.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpbool.o: /usr/include/sys/stat.h /usr/include/string.h
atpbool.o: /usr/include/signal.h /usr/include/sys/signal.h
atpbool.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpbool.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpbool.o: /usr/include/memory.h /usr/include/stdio.h
atpcase.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpcase.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpcase.o: /usr/include/sys/stat.h /usr/include/string.h
atpcase.o: /usr/include/signal.h /usr/include/sys/signal.h
atpcase.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpcase.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpcase.o: /usr/include/memory.h /usr/include/stdio.h
atpcheck.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpcheck.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpcheck.o: /usr/include/sys/stat.h /usr/include/string.h
atpcheck.o: /usr/include/signal.h /usr/include/sys/signal.h
atpcheck.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpcheck.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpcheck.o: /usr/include/memory.h /usr/include/stdio.h
atpchois.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpchois.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpchois.o: /usr/include/sys/stat.h /usr/include/string.h
atpchois.o: /usr/include/signal.h /usr/include/sys/signal.h
atpchois.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpchois.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpchois.o: /usr/include/memory.h /usr/include/stdio.h
atpcmd.o: /usr/include/string.h /usr/include/setjmp.h /usr/include/varargs.h
atpcmd.o: atph.h atpsysex.h /usr/include/stddef.h /usr/include/sys/stdsyms.h
atpcmd.o: /usr/include/sys/types.h /usr/include/sys/stat.h
atpcmd.o: /usr/include/signal.h /usr/include/sys/signal.h
atpcmd.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpcmd.o: /usr/include/assert.h /usr/include/malloc.h /usr/include/memory.h
atpcmd.o: /usr/include/stdio.h atpframh.h
atpcmplx.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpcmplx.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpcmplx.o: /usr/include/sys/stat.h /usr/include/string.h
atpcmplx.o: /usr/include/signal.h /usr/include/sys/signal.h
atpcmplx.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpcmplx.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpcmplx.o: /usr/include/memory.h /usr/include/stdio.h
atpdebug.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpdebug.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpdebug.o: /usr/include/sys/stat.h /usr/include/string.h
atpdebug.o: /usr/include/signal.h /usr/include/sys/signal.h
atpdebug.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpdebug.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpdebug.o: /usr/include/memory.h /usr/include/stdio.h
atpdynam.o: /usr/include/stdlib.h /usr/include/stdio.h
atpdynam.o: /usr/include/sys/stdsyms.h /usr/include/varargs.h atph.h
atpdynam.o: atpsysex.h /usr/include/stddef.h /usr/include/sys/types.h
atpdynam.o: /usr/include/sys/stat.h /usr/include/string.h
atpdynam.o: /usr/include/signal.h /usr/include/sys/signal.h
atpdynam.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpdynam.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpdynam.o: /usr/include/memory.h
atperror.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h
atperror.o: /usr/include/malloc.h /usr/include/sys/types.h
atperror.o: /usr/include/string.h /usr/include/setjmp.h
atperror.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atperror.o: /usr/include/sys/stat.h /usr/include/signal.h
atperror.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atperror.o: /usr/include/ctype.h /usr/include/assert.h /usr/include/memory.h
atperror.o: atpframh.h
atpfindp.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atpfindp.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpfindp.o: /usr/include/sys/stat.h /usr/include/string.h
atpfindp.o: /usr/include/signal.h /usr/include/sys/signal.h
atpfindp.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpfindp.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpfindp.o: /usr/include/memory.h /usr/include/stdio.h
atpframe.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atpframe.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpframe.o: /usr/include/sys/stat.h /usr/include/string.h
atpframe.o: /usr/include/signal.h /usr/include/sys/signal.h
atpframe.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpframe.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpframe.o: /usr/include/memory.h /usr/include/stdio.h atpframh.h
atphelp.o: /usr/include/stdlib.h /usr/include/limits.h
atphelp.o: /usr/include/sys/stdsyms.h /usr/include/sys/param.h
atphelp.o: /usr/include/sys/types.h /usr/include/machine/param.h
atphelp.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
atphelp.o: /usr/include/values.h /usr/include/string.h /usr/include/varargs.h
atphelp.o: atph.h atpsysex.h /usr/include/stddef.h /usr/include/sys/stat.h
atphelp.o: /usr/include/signal.h /usr/include/sys/signal.h
atphelp.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atphelp.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atphelp.o: /usr/include/memory.h /usr/include/stdio.h atpframh.h
atphelpc.o: /usr/include/string.h /usr/include/varargs.h atph.h atpsysex.h
atphelpc.o: /usr/include/stddef.h /usr/include/sys/stdsyms.h
atphelpc.o: /usr/include/sys/types.h /usr/include/sys/stat.h
atphelpc.o: /usr/include/signal.h /usr/include/sys/signal.h
atphelpc.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atphelpc.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atphelpc.o: /usr/include/memory.h /usr/include/stdio.h atpframh.h
atphexpm.o: /usr/include/ctype.h /usr/include/stdlib.h atph.h
atphexpm.o: /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atphexpm.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atphexpm.o: /usr/include/sys/stat.h /usr/include/string.h
atphexpm.o: /usr/include/signal.h /usr/include/sys/signal.h
atphexpm.o: /usr/include/sys/syscall.h /usr/include/setjmp.h
atphexpm.o: /usr/include/assert.h /usr/include/malloc.h /usr/include/memory.h
atphexpm.o: /usr/include/stdio.h
atpinit.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h
atpinit.o: /usr/include/stdlib.h /usr/include/signal.h
atpinit.o: /usr/include/sys/signal.h /usr/include/sys/types.h
atpinit.o: /usr/include/sys/syscall.h /usr/include/sys/ioctl.h
atpinit.o: /usr/include/termios.h /usr/include/sys/termio.h
atpinit.o: /usr/include/setjmp.h /usr/include/unistd.h
atpinit.o: /usr/include/sys/unistd.h atph.h /usr/include/varargs.h atpsysex.h
atpinit.o: /usr/include/stddef.h /usr/include/sys/stat.h
atpinit.o: /usr/include/string.h /usr/include/ctype.h /usr/include/assert.h
atpinit.o: /usr/include/malloc.h /usr/include/memory.h
atpkeywd.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef,h
atpkeywd.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpkeywd.o: /usr/include/sys/stat.h /usr/include/string.h
atpkeywd.o: /usr/include/signal.h /usr/include/sys/signal.h
atpkeywd.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpkeywd.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpkeywd.o: /usr/include/memory.h /usr/include/stdio.h
atplist.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atplist.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atplist.o: /usr/include/sys/stat.h /usr/include/string.h
atplist.o: /usr/include/signal.h /usr/include/sys/signal.h
atplist.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atplist.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atplist.o: /usr/include/memory.h /usr/include/stdio.h
atpmanpg.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h
atpmanpg.o: /usr/include/stdlib.h /usr/include/string.h /usr/include/limits.h
atpmanpg.o: /usr/include/sys/param.h /usr/include/sys/types.h
atpmanpg.o: /usr/include/machine/param.h /usr/include/sys/sysmacros.h
atpmanpg.o: /usr/include/sys/time.h /usr/include/varargs.h atph.h atpsysex.h
atpmanpg.o: /usr/include/stddef.h /usr/include/sys/stat.h
atpmanpg.o: /usr/include/signal.h /usr/include/sys/signal.h
atpmanpg.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpmanpg.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpmanpg.o: /usr/include/memory.h atpframh.h
atpmem.o: /usr/include/string.h /usr/include/varargs.h atph.h atpsysex.h
atpmem.o: /usr/include/stddef.h /usr/include/sys/stdsyms.h
atpmem.o: /usr/include/sys/types.h /usr/include/sys/stat.h
atpmem.o: /usr/include/signal.h /usr/include/sys/signal.h
atpmem.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpmem.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpmem.o: /usr/include/memory.h /usr/include/stdio.h
atpnullp.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpnullp.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpnullp.o: /usr/include/sys/stat.h /usr/include/string.h
atpnullp.o: /usr/include/signal.h /usr/include/sys/signal.h
atpnullp.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpnullp.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpnullp.o: /usr/include/memory.h /usr/include/stdio.h
atpnum.o: /usr/include/limits.h /usr/include/sys/stdsyms.h
atpnum.o: /usr/include/sys/param.h /usr/include/sys/types.h
atpnum.o: /usr/include/machine/param.h /usr/include/sys/sysmacros.h
atpnum.o: /usr/include/sys/time.h /usr/include/ctype.h /usr/include/errno.h
atpnum.o: /usr/include/sys/errno.h /usr/include/stdlib.h
atpnum.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atpnum.o: /usr/include/sys/stat.h /usr/include/string.h /usr/include/signal.h
atpnum.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpnum.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpnum.o: /usr/include/memory.h /usr/include/stdio.h
atppage.o: /usr/include/stdlib.h /usr/include/sys/stat.h
atppage.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atppage.o: /usr/include/unistd.h /usr/include/sys/unistd.h
atppage.o: /usr/include/errno.h /usr/include/sys/errno.h
atppage.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atppage.o: /usr/include/string.h /usr/include/signal.h
atppage.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atppage.o: /usr/include/ctype.h /usr/include/setjmp.h /usr/include/assert.h
atppage.o: /usr/include/malloc.h /usr/include/memory.h /usr/include/stdio.h
atppage.o: atpframh.h
atpparse.o: /usr/include/string.h /usr/include/setjmp.h
atpparse.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atpparse.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpparse.o: /usr/include/sys/stat.h /usr/include/signal.h
atpparse.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpparse.o: /usr/include/ctype.h /usr/include/assert.h /usr/include/malloc.h
atpparse.o: /usr/include/memory.h /usr/include/stdio.h atpframh.h
atppmchk.o: /usr/include/varargs.h atph.h atpsysex.h /usr/include/stddef.h
atppmchk.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atppmchk.o: /usr/include/sys/stat.h /usr/include/string.h
atppmchk.o: /usr/include/signal.h /usr/include/sys/signal.h
atppmchk.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atppmchk.o: /usr/include/setjmp.h /usr/include/assert .h /usr/include/malloc.h
atppmchk.o: /usr/include/memory.h /usr/include/stdio.h
atppmdef.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atppmdef.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atppmdef.o: /usr/include/sys/stat.h /usr/include/string.h
atppmdef.o: /usr/include/signal.h /usr/include/sys/signal.h
atppmdef.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atppmdef.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atppmdef.o: /usr/include/memory.h /usr/include/stdio.h
atppmptr.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atppmptr.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atppmptr.o: /usr/include/sys/stat.h /usr/include/string.h
atppmptr.o: /usr/include/signal.h /usr/include/sys/signal.h
atppmptr.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atppmptr.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atppmptr.o: /usr/include/memory.h /usr/include/stdio.h
atprpblk.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atprpblk.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atprpblk.o: /usr/include/sys/stat.h /usr/include/string.h
atprpblk.o: /usr/include/signal.h /usr/include/sys/signal.h
atprpblk.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atprpblk.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atprpblk.o: /usr/include/memory.h /usr/include/stdio.h
atpstcmp.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpstcmp.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpstcmp.o: /usr/include/sys/stat.h /usr/include/string.h
atpstcmp.o: /usr/include/signal.h /usr/include/sys/signal.h
atpstcmp.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atpstcmp.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atpstcmp.o: /usr/include/memory.h /usr/include/stdio.h
atpstr.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpstr.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atpstr.o: /usr/include/sys/stat.h /usr/include/string.h /usr/include/signal.h
atpstr.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpstr.o: /usr/include/ctype.h /usr/include/setjmp.h /usr/include/assert.h
atpstr.o: /usr/include/malloc.h /usr/include/memory.h /usr/include/stdio.h
atptoken.o: atph.h /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atptoken.o: /usr/include/sys/stdsyms.h /usr/include/sys/types.h
atptoken.o: /usr/include/sys/stat.h /usr/include/string.h
atptoken.o: /usr/include/signal.h /usr/include/sys/signal.h
atptoken.o: /usr/include/sys/syscall.h /usr/include/ctype.h
atptoken.o: /usr/include/setjmp.h /usr/include/assert.h /usr/include/malloc.h
atptoken.o: /usr/include/memory.h /usr/include/stdio.h
atpusrio.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h atph.h
atpusrio.o: /usr/include/varargs.h atpsysex.h /usr/include/stddef.h
atpusrio.o: /usr/include/sys/types.h /usr/include/sys/stat.h
atpusrio.o: /usr/include/string.h /usr/include/signal.h
atpusrio.o: /usr/include/sys/signal.h /usr/include/sys/syscall.h
atpusrio.o: /usr/include/ctype.h /usr/include/setjmp.h /usr/include/assert.h
atpusrio.o: /usr/include/malloc.h /usr/include/memory.h
atpexmp.o: /usr/include/stdio.h /usr/include/sys/stdsyms.h
atpexmp.o: /usr/include/stdlib.h /usr/include/limits.h
atpexmp.o: /usr/include/sys/param.h /usr/include/sys/types.h
atpexmp.o: /usr/include/machine/param.h /usr/include/sys/sysmacros.h
atpexmp.o: /usr/include/sys/time.h /usr/include/malloc.h /usr/include/math.h
atpexmp.o: /usr/include/sys/times.h /usr/include/string.h
atpexmp.o: /usr/include/strings.h /usr/include/ctype.h /usr/include/errno.h
atpexmp.o: /usr/include/sys/errno.h
atpexmp.o: /itdserv/Contexts/g2config.aa07/tcl/inc/tel.h
atpexmp.o: /itdserv/Contexts/g2config.aa07/genia/inc/slp.h atph.h
atpexmp.o: /usr/include/varargs.h atp2tclh.h

